apiVersion: v1
kind: Service
metadata:
  namespace: 'exam'
  name: prestashop-service
spec:
  type: NodePort
  selector:
    app: prestashop
  ports:
    - port: 80
      nodePort: 30000
      name: http
