apiVersion: v1
kind: Secret
metadata:
  name: exam-secret
  namespace: exam
type: Opaque
data:
  PRESTASHOP_DATABASE_USER: dXNlcg==
  PRESTASHOP_DATABASE_PASSWORD: cGFzc3dvcmQ=
  PRESTASHOP_DATABASE_NAME: cHJlc3Rhc2hvcA==
